package com.smartcart.ai.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.smartcart.ai.entity.Product;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Outbound DTO returned by /api/chat/recommend.
 * Contains the AI-style summary and the ranked product results.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class RecommendationResponse {

    /** Natural-language summary generated by the recommendation engine */
    private String summary;

    /** Detected category from the user's query */
    private String category;

    /** Detected budget ceiling in ₹. Null if no budget was mentioned in the query. */
    private Long budget;

    /** Primary detected use-case (e.g., "coding", "gaming", "camera"). Null if not detected. */
    private String useCase;

    /** Top 5 recommended products ranked by score */
    private List<Product> products;

    /**
     * Top 3 products for the comparison table.
     * Always a subset of products (max 3 items).
     */
    private List<Product> topProducts;

    /** Total number of matching products before ranking */
    private int totalMatches;

    /** Error message if the query could not be handled */
    private String error;
}
